### ISSUE TITLE
DependencyError

### ISSUE THREAD

**Issue by regNec** [teamnsrg/erays#2]
When I tried to run the program using 

>$ python structurer.py temp/temp.hex

 an error was raised.
The error message is 
`raise DependencyError("cannot resolve byte code read dependency")
ceptions.DependencyError: cannot resolve byte code read dependency`
The environment is Ubuntu 18.04.1, python 2.7.15
So how can I solve this problem?
Thank you :)

**Comment by kumarde** [comment]
Could you provide us with the contents of `temp/temp.hex` ?

**Comment by gsalzer** [comment]
The first character of `temp/temp.hex` should be `6` instead of `9`; `solc` code starts with `60` ...

**Comment by kumarde** [comment]
You're right - this is an error on our part. Don't know what happened. Updated the README to point to a working example.

**Comment by gsalzer** [comment]
Well, temp.hex IS a working example, you just have to change the first
character from 9 to 6.  The pseudo-code generated by your tool then
corresponds exactly to the solidity code in temp.sol

Removing the file is a bit of an over-reaction ;-)
